name = "aka-mcp"
description = "An Akamai Functions MCP Server"
homepage = "https://github.com/ThorstenHans/akamai-functions-mcp"
version = "0.1.0"
spin_compatibility = ">=2.0.0"
license = "Apache-2.0"
package = "aka-mcp"
